const ERROR_CODES = {
  1: 'unauthenticated req at createCampground',
  2: 'Images exceeded the limit',
  3: 'geocoding failed',
  4: 'author mismatch at create CG',
  5: 'campgrounds table error',
  6: 'fetch error: <get-campgrounds-by-search-term>',
  7: 'fetch error: <get-cgs-by-user-id>',
  8: 'fetch error: <get-cgs-by-user-id>',
  9: 'unauthenticated req at updateCampground',
  10: 'unauthorized req at updateCampground',
  11: 'Images exceeded the limit',
  12: 'geocoding failed',
  13: '<uploadthing-delete-error>',
  14: 'error: <update-campgrounds>',
  15: 'unauthenticated req at deleteCampground',
  16: 'unauthorized req at deleteCampground',
  17: '<uploadthing-delete-error>',
  18: 'db query failed at delete-campground-by-id',
  19: 'contactinfoDB <add-contacts> error',
  20: 'no keys',
  21: 'imgDB <add-img> error',
  22: 'imgDB query error',
  23: 'error <getImagesByCampgroundID>',
  24: 'error in: <deleteImagesByCampgroundID>',
  25: 'error in: <deleteImagesByCampgroundID>',
  26: '<uploadthing-delete-error>',
  27: 'unauthenticated req at createReview',
  28: 'fetchReviewsByCampIDQueryError',
  29: 'fetchReviewsByReviewIDQueryError',
  30: 'unauthenticated req at editReview',
  31: 'unauthorized req at editReview',
  32: 'unauthenticated req at editReview',
  33: 'unauthorized req at editReview',
  34: 'DeleteReviewByIdError',
  35: 'update-user-data error',
  36: 'passwords mismatch <confirm-pass !== new-pass> changePassword',
  37: `Current Passwords didn't match at changePassword`,
  38: 'db fetch error for current-password comparision',
  39: 'change-password error',
  40: `Current Passwords didn't match at deleteUser`,
  41: 'db fetch error for current-password comparision at deleteUser',
  42: 'change-password error',
};